#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import traceback

try:
    sys.path.insert(0,os.getcwd())
    import cumodoro

    cumodoro.main()
except Exception as error:
    print(traceback.format_exc())
    print(str(error))

    sys.exit(1)

